-- firefly.Electrolyser definition

CREATE TABLE `Electrolyser` (
  `logged` datetime(2) NOT NULL DEFAULT current_timestamp(2),
  `name` varchar(25) NOT NULL,
  `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `flow` float DEFAULT NULL,
  `volts` float DEFAULT NULL,
  `amps` float DEFAULT NULL,
  `temperature` float DEFAULT NULL,
  `errors` text DEFAULT NULL,
  `waterPressure` float DEFAULT NULL,
  `rate` float DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=279203 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- firefly.ElectrolyserRequests definition

CREATE TABLE `ElectrolyserRequests` (
  `logged` datetime(3) NOT NULL DEFAULT current_timestamp(3),
  `RateRequested` int(11) DEFAULT NULL,
  PRIMARY KEY (`logged`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- firefly.IOValues definition

CREATE TABLE `IOValues` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `logged` datetime(3) NOT NULL DEFAULT current_timestamp(3),
  `a0` smallint(6) NOT NULL,
  `a1` smallint(6) NOT NULL,
  `a2` smallint(6) NOT NULL,
  `a3` smallint(6) NOT NULL,
  `a4` smallint(6) NOT NULL,
  `a5` smallint(6) NOT NULL,
  `a6` smallint(6) NOT NULL,
  `a7` smallint(6) NOT NULL,
  `inputs` tinyint(3) unsigned NOT NULL,
  `outputs` tinyint(3) unsigned NOT NULL,
  `relays` smallint(5) unsigned NOT NULL,
  `ACVolts` float NOT NULL,
  `ACAmps` float NOT NULL,
  `ACWatts` float NOT NULL,
  `ACHertz` float NOT NULL,
  `vref` smallint(6) DEFAULT NULL,
  `cpuTemp` smallint(6) DEFAULT NULL,
  `rawCpuTemp` smallint(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `IOValues_logged_IDX` (`logged`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=10575548 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- firefly.PANFuelCell definition

CREATE TABLE `PANFuelCell` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `StackCurrent` smallint(5) unsigned DEFAULT NULL,
  `StackVoltage` smallint(5) unsigned DEFAULT NULL,
  `CoolantInTemp` smallint(6) DEFAULT NULL,
  `CoolantOutTemp` smallint(6) DEFAULT NULL,
  `logged` datetime(3) DEFAULT current_timestamp(3),
  `OutputVoltage` smallint(6) DEFAULT NULL,
  `OutputCurrent` smallint(6) DEFAULT NULL,
  `CoolantFanSpeed` smallint(5) unsigned DEFAULT NULL,
  `CoolantPumpSpeed` smallint(5) unsigned DEFAULT NULL,
  `CoolantPumpVolts` tinyint(3) unsigned DEFAULT NULL,
  `CoolantPumpAmps` tinyint(3) unsigned DEFAULT NULL,
  `InsulationResistance` smallint(5) unsigned DEFAULT NULL,
  `HydrogenPressure` smallint(5) unsigned DEFAULT NULL,
  `AirPressure` smallint(5) unsigned DEFAULT NULL,
  `CoolantPressure` smallint(5) unsigned DEFAULT NULL,
  `AirinletTemp` smallint(6) DEFAULT NULL,
  `AmbientTemp` smallint(6) DEFAULT NULL,
  `AirFlow` smallint(5) unsigned DEFAULT NULL,
  `HydrogenConcentration` tinyint(3) unsigned DEFAULT NULL,
  `DCDCTemp` tinyint(3) unsigned DEFAULT NULL,
  `DCDCInVolts` smallint(5) unsigned DEFAULT NULL,
  `DCDCOutVolts` smallint(5) unsigned DEFAULT NULL,
  `DCDCInAmps` smallint(5) unsigned DEFAULT NULL,
  `DCDCOutAmps` smallint(5) unsigned DEFAULT NULL,
  `MinCellVolts` smallint(5) unsigned DEFAULT NULL,
  `MaxCellVolts` smallint(5) unsigned DEFAULT NULL,
  `AvgCellVolts` smallint(5) unsigned DEFAULT NULL,
  `IdxMaxCell` tinyint(3) unsigned DEFAULT NULL,
  `IdxMinCell` tinyint(3) unsigned DEFAULT NULL,
  `RunStage` tinyint(3) unsigned DEFAULT NULL,
  `FaultLevel` tinyint(3) unsigned DEFAULT NULL,
  `PowerModeState` tinyint(3) unsigned DEFAULT NULL,
  `Cell30Volts` smallint(6) DEFAULT NULL,
  `Cell00Volts` smallint(6) DEFAULT NULL,
  `Cell01Volts` smallint(6) DEFAULT NULL,
  `Cell02Volts` smallint(6) DEFAULT NULL,
  `Cell03Volts` smallint(6) DEFAULT NULL,
  `Cell04Volts` smallint(6) DEFAULT NULL,
  `Cell05Volts` smallint(6) DEFAULT NULL,
  `Cell06Volts` smallint(6) DEFAULT NULL,
  `Cell07Volts` smallint(6) DEFAULT NULL,
  `Cell08Volts` smallint(6) DEFAULT NULL,
  `Cell09Volts` smallint(6) DEFAULT NULL,
  `Cell10Volts` smallint(6) DEFAULT NULL,
  `Cell11Volts` smallint(6) DEFAULT NULL,
  `Cell12Volts` smallint(6) DEFAULT NULL,
  `Cell13Volts` smallint(6) DEFAULT NULL,
  `Cell14Volts` smallint(6) DEFAULT NULL,
  `Cell15Volts` smallint(6) DEFAULT NULL,
  `Cell16Volts` smallint(6) DEFAULT NULL,
  `Cell17Volts` smallint(6) DEFAULT NULL,
  `Cell18Volts` smallint(6) DEFAULT NULL,
  `Cell19Volts` smallint(6) DEFAULT NULL,
  `Cell20Volts` smallint(6) DEFAULT NULL,
  `Cell21Volts` smallint(6) DEFAULT NULL,
  `Cell22Volts` smallint(6) DEFAULT NULL,
  `Cell23Volts` smallint(6) DEFAULT NULL,
  `Cell24Volts` smallint(6) DEFAULT NULL,
  `Cell25Volts` smallint(6) DEFAULT NULL,
  `Cell26Volts` smallint(6) DEFAULT NULL,
  `Cell27Volts` smallint(6) DEFAULT NULL,
  `Cell28Volts` smallint(6) DEFAULT NULL,
  `Cell29Volts` smallint(6) DEFAULT NULL,
  `Cell31Volts` smallint(6) DEFAULT NULL,
  `Alarms` int(10) unsigned DEFAULT NULL,
  `PowerRequested` smallint(5) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `PANFuelCell_logged_IDX` (`logged`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=7491789 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- firefly.calibration definition

CREATE TABLE `calibration` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `measured` smallint(5) unsigned NOT NULL,
  `Observed` float NOT NULL,
  `device` varchar(25) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- firefly.logging definition

CREATE TABLE `logging` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `logged` datetime DEFAULT current_timestamp(),
  `el1Rate` int(11) DEFAULT NULL,
  `el1ElectrolyteLevel` varchar(25) DEFAULT NULL,
  `el1ElectrolyteTemp` smallint(6) DEFAULT NULL,
  `el1StateCode` smallint(6) DEFAULT NULL,
  `el1H2Flow` smallint(6) DEFAULT NULL,
  `el1H2InnerPressure` smallint(6) DEFAULT NULL,
  `el1H2OuterPressure` smallint(6) DEFAULT NULL,
  `el1StackVoltage` smallint(6) DEFAULT NULL,
  `el1StackCurrent` smallint(6) DEFAULT NULL,
  `el1SystemStateCode` smallint(6) DEFAULT NULL,
  `el1WaterPressure` smallint(6) DEFAULT NULL,
  `drTemp0` smallint(6) DEFAULT NULL,
  `drTemp1` smallint(6) DEFAULT NULL,
  `drTemp2` smallint(6) DEFAULT NULL,
  `drTemp3` smallint(6) DEFAULT NULL,
  `drInputPressure` smallint(6) DEFAULT NULL,
  `drOutputPressure` smallint(6) DEFAULT NULL,
  `drWarning` varchar(1024) DEFAULT NULL,
  `drError` varchar(1024) DEFAULT NULL,
  `el0Rate` int(11) DEFAULT NULL,
  `el0ElectrolyteLevel` varchar(25) DEFAULT NULL,
  `el0ElectrolyteTemp` smallint(6) DEFAULT NULL,
  `el0StateCode` smallint(6) DEFAULT NULL,
  `el0H2Flow` smallint(6) DEFAULT NULL,
  `el0H2InnerPressure` smallint(6) DEFAULT NULL,
  `el0H2OuterPressure` smallint(6) DEFAULT NULL,
  `el0StackVoltage` smallint(6) DEFAULT NULL,
  `el0StackCurrent` smallint(6) DEFAULT NULL,
  `el0SystemStateCode` smallint(6) DEFAULT NULL,
  `el0WaterPressure` smallint(6) DEFAULT NULL,
  `fc1State` varchar(25) DEFAULT NULL,
  `fc1AnodePressure` smallint(6) DEFAULT NULL,
  `fc1FaultFlagA` int(10) unsigned DEFAULT NULL,
  `fc1FaultFlagB` int(10) unsigned DEFAULT NULL,
  `fc1FaultFlagC` int(10) unsigned DEFAULT NULL,
  `fc1FaultFlagD` int(10) unsigned DEFAULT NULL,
  `fc1InletTemp` smallint(6) DEFAULT NULL,
  `fc1OutletTemp` smallint(6) DEFAULT NULL,
  `fc1OutputPower` smallint(6) DEFAULT NULL,
  `fc1OutputCurrent` smallint(6) DEFAULT NULL,
  `fc1OutputVoltage` smallint(6) DEFAULT NULL,
  `fc0State` varchar(25) DEFAULT NULL,
  `fc0AnodePressure` smallint(6) DEFAULT NULL,
  `fc0FaultFlagA` int(10) unsigned DEFAULT NULL,
  `fc0FaultFlagB` int(10) unsigned DEFAULT NULL,
  `fc0FaultFlagC` int(10) unsigned DEFAULT NULL,
  `fc0FaultFlagD` int(10) unsigned DEFAULT NULL,
  `fc0InletTemp` smallint(6) DEFAULT NULL,
  `fc0OutletTemp` smallint(6) DEFAULT NULL,
  `fc0OutputPower` smallint(6) DEFAULT NULL,
  `fc0OutputCurrent` smallint(6) DEFAULT NULL,
  `fc0OutputVoltage` smallint(6) DEFAULT NULL,
  `gasFuelCellPressure` smallint(5) unsigned DEFAULT NULL COMMENT 'in tenths of a mBar',
  `gasTankPressure` smallint(5) unsigned DEFAULT NULL COMMENT 'in units of mBar',
  `totalDissolvedSolids` smallint(5) unsigned DEFAULT NULL COMMENT 'in hundredths of a uS/cm',
  `relayGas` tinyint(1) DEFAULT NULL,
  `relayFuelCell1Enable` tinyint(1) DEFAULT NULL,
  `relayFuelCell1Run` tinyint(1) DEFAULT NULL,
  `relayFuelCell0Enable` tinyint(1) DEFAULT NULL,
  `relayFuelCell0Run` tinyint(1) DEFAULT NULL,
  `relayEl1Power` tinyint(1) DEFAULT NULL,
  `relayEl0Power` tinyint(1) DEFAULT NULL,
  `relaySpare` tinyint(1) DEFAULT NULL,
  `ACPower` int(10) unsigned DEFAULT NULL,
  `ACVolts` smallint(5) unsigned DEFAULT NULL,
  `ACCurrent` int(10) unsigned DEFAULT NULL,
  `ACFrequency` smallint(5) unsigned DEFAULT NULL,
  `ACPowerFactor` tinyint(3) unsigned DEFAULT NULL,
  `HPPower` int(10) unsigned DEFAULT NULL,
  `HPVolts` smallint(5) unsigned DEFAULT NULL,
  `HPCurrent` int(10) unsigned DEFAULT NULL,
  `HPFrequency` smallint(5) unsigned DEFAULT NULL,
  `HPPowerFactor` tinyint(3) unsigned DEFAULT NULL,
  `ACEnergy` int(10) unsigned DEFAULT NULL,
  `HPEnergy` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `logging_logged_IDX` (`logged`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=21628981 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- firefly.logging_archive definition

CREATE TABLE `logging_archive` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `logged` datetime DEFAULT curdate(),
  `el0Rate` int(11) DEFAULT NULL,
  `el0ElectrolyteLevel` varchar(25) DEFAULT NULL,
  `el0ElectrolyteTemp` smallint(6) DEFAULT NULL,
  `el0StateCode` smallint(6) DEFAULT NULL,
  `el1H2Flow` smallint(6) DEFAULT NULL,
  `el1H2InnerPressure` smallint(6) DEFAULT NULL,
  `el1H2OuterPressure` smallint(6) DEFAULT NULL,
  `el1StackVoltage` smallint(6) DEFAULT NULL,
  `el1StackCurrent` smallint(6) DEFAULT NULL,
  `el1SystemStateCode` smallint(6) DEFAULT NULL,
  `el1WaterPressure` smallint(6) DEFAULT NULL,
  `drTemp0` smallint(6) DEFAULT NULL,
  `drTemp1` smallint(6) DEFAULT NULL,
  `drTemp2` smallint(6) DEFAULT NULL,
  `drTemp3` smallint(6) DEFAULT NULL,
  `drInputPressure` smallint(6) DEFAULT NULL,
  `drOutputPressure` smallint(6) DEFAULT NULL,
  `drWarning` varchar(1024) DEFAULT NULL,
  `drError` varchar(1024) DEFAULT NULL,
  `el1Rate` int(11) DEFAULT NULL,
  `el1ElectrolyteLevel` varchar(25) DEFAULT NULL,
  `el1ElectrolyteTemp` smallint(6) DEFAULT NULL,
  `el1StateCode` smallint(6) DEFAULT NULL,
  `el0H2Flow` smallint(6) DEFAULT NULL,
  `el0H2InnerPressure` smallint(6) DEFAULT NULL,
  `el0H2OuterPressure` smallint(6) DEFAULT NULL,
  `el0StackVoltage` smallint(6) DEFAULT NULL,
  `el0StackCurrent` smallint(6) DEFAULT NULL,
  `el0SystemStateCode` smallint(6) DEFAULT NULL,
  `el0WaterPressure` smallint(6) DEFAULT NULL,
  `fc1State` varchar(25) DEFAULT NULL,
  `fc1AnodePressure` smallint(6) DEFAULT NULL,
  `fc1FaultFlagA` int(10) unsigned DEFAULT NULL,
  `fc1FaultFlagB` int(10) unsigned DEFAULT NULL,
  `fc1FaultFlagC` int(10) unsigned DEFAULT NULL,
  `fc1FaultFlagD` int(10) unsigned DEFAULT NULL,
  `fc1InletTemp` smallint(6) DEFAULT NULL,
  `fc1OutletTemp` smallint(6) DEFAULT NULL,
  `fc1OutputPower` smallint(6) DEFAULT NULL,
  `fc1OutputCurrent` smallint(6) DEFAULT NULL,
  `fc1OutputVoltage` smallint(6) DEFAULT NULL,
  `fc0State` varchar(25) DEFAULT NULL,
  `fc0AnodePressure` smallint(6) DEFAULT NULL,
  `fc0FaultFlagA` int(10) unsigned DEFAULT NULL,
  `fc0FaultFlagB` int(10) unsigned DEFAULT NULL,
  `fc0FaultFlagC` int(10) unsigned DEFAULT NULL,
  `fc0FaultFlagD` int(10) unsigned DEFAULT NULL,
  `fc0InletTemp` smallint(6) DEFAULT NULL,
  `fc0OutletTemp` smallint(6) DEFAULT NULL,
  `fc0OutputPower` smallint(6) DEFAULT NULL,
  `fc0OutputCurrent` smallint(6) DEFAULT NULL,
  `fc0OutputVoltage` smallint(6) DEFAULT NULL,
  `gasFuelCellPressure` smallint(5) unsigned DEFAULT NULL,
  `gasTankPressure` smallint(5) unsigned DEFAULT NULL,
  `totalDissolvedSolids` smallint(5) unsigned DEFAULT NULL,
  `relayGas` tinyint(1) DEFAULT NULL,
  `relayFuelCell1Enable` tinyint(1) DEFAULT NULL,
  `relayFuelCell1Run` tinyint(1) DEFAULT NULL,
  `relayFuelCell0Enable` tinyint(1) DEFAULT NULL,
  `relayFuelCell0Run` tinyint(1) DEFAULT NULL,
  `relayEl1Power` tinyint(1) DEFAULT NULL,
  `relayEl0Power` tinyint(1) DEFAULT NULL,
  `relaySpare` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=432827 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;